//This file is automatically generated by generator.lua from https://github.com/goossens/ImGuiColorTextEdit
//based on TextEditor.h file version XXX from https://github.com/goossens/ImGuiColorTextEdit
#include "imgui.h"
#include "imgui_internal.h"
#include "./ImGuiColorTextEdit/TextEditor.h"
#include "./ImGuiColorTextEdit/TextDiff.h"
#include "./ImGuiColorTextEdit/extras/TrieAutoComplete.h"
#include "./ImGuiColorTextEdit/extras/Notifications.h"
#include "./ImGuiColorTextEdit/example/dejavu.h"
#include "cimCTE.h"
#include <cstring>


static inline DocPos ConvertToCPP_DocPos(const DocPos_c& src)
{
    DocPos dest;
    dest.line = src.line;
    dest.index = src.index;
    return dest;
}
static inline DocPos_c ConvertFromCPP_DocPos(const DocPos& src)
{
    DocPos_c dest;
    dest.line = src.line;
    dest.index = src.index;
    return dest;
}
static inline DocSelection ConvertToCPP_DocSelection(const DocSelection_c& src)
{
    DocSelection dest;
    dest.start.line = src.start.line;
    dest.start.index = src.start.index;
    dest.end.line = src.end.line;
    dest.end.index = src.end.index;
    return dest;
}
static inline DocSelection_c ConvertFromCPP_DocSelection(const DocSelection& src)
{
    DocSelection_c dest;
    dest.start.line = src.start.line;
    dest.start.index = src.start.index;
    dest.end.line = src.end.line;
    dest.end.index = src.end.index;
    return dest;
}
static inline ImVec2 ConvertToCPP_ImVec2(const ImVec2_c& src)
{
    ImVec2 dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}
static inline ImVec2_c ConvertFromCPP_ImVec2(const ImVec2& src)
{
    ImVec2_c dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}
static inline VisPos ConvertToCPP_VisPos(const VisPos_c& src)
{
    VisPos dest;
    dest.row = src.row;
    dest.column = src.column;
    return dest;
}
static inline VisPos_c ConvertFromCPP_VisPos(const VisPos& src)
{
    VisPos_c dest;
    dest.row = src.row;
    dest.column = src.column;
    return dest;
}CIMGUI_API TextEditor* TextEditor_TextEditor(void)
{
    return IM_NEW(TextEditor)();
}
CIMGUI_API void TextEditor_destroy(TextEditor* self)
{
    IM_DELETE(self);
}
CIMGUI_API DocPos* DocPos_DocPos_Nil(void)
{
    return IM_NEW(DocPos)();
}
CIMGUI_API void DocPos_destroy(DocPos* self)
{
    IM_DELETE(self);
}
CIMGUI_API DocPos* DocPos_DocPos_size_t(size_t line,size_t index)
{
    return IM_NEW(DocPos)(line,index);
}
CIMGUI_API DocSelection* DocSelection_DocSelection_Nil(void)
{
    return IM_NEW(DocSelection)();
}
CIMGUI_API void DocSelection_destroy(DocSelection* self)
{
    IM_DELETE(self);
}
CIMGUI_API DocSelection* DocSelection_DocSelection_DocPos(DocPos_c start,DocPos_c end)
{
    return IM_NEW(DocSelection)(ConvertToCPP_DocPos(start),ConvertToCPP_DocPos(end));
}
CIMGUI_API VisPos* VisPos_VisPos_Nil(void)
{
    return IM_NEW(VisPos)();
}
CIMGUI_API void VisPos_destroy(VisPos* self)
{
    IM_DELETE(self);
}
CIMGUI_API VisPos* VisPos_VisPos_size_t(size_t row,size_t column)
{
    return IM_NEW(VisPos)(row,column);
}
CIMGUI_API void TextEditor_SetTabSize(TextEditor* self,size_t value)
{
    return self->SetTabSize(value);
}
CIMGUI_API size_t TextEditor_GetTabSize(TextEditor* self)
{
    return self->GetTabSize();
}
CIMGUI_API void TextEditor_SetInsertSpacesOnTabs(TextEditor* self,bool value)
{
    return self->SetInsertSpacesOnTabs(value);
}
CIMGUI_API bool TextEditor_IsInsertSpacesOnTabs(TextEditor* self)
{
    return self->IsInsertSpacesOnTabs();
}
CIMGUI_API void TextEditor_SetLineSpacing(TextEditor* self,float value)
{
    return self->SetLineSpacing(value);
}
CIMGUI_API float TextEditor_GetLineSpacing(TextEditor* self)
{
    return self->GetLineSpacing();
}
CIMGUI_API void TextEditor_SetWordWrapEnabled(TextEditor* self,bool value)
{
    return self->SetWordWrapEnabled(value);
}
CIMGUI_API bool TextEditor_IsWordWrapEnabled(TextEditor* self)
{
    return self->IsWordWrapEnabled();
}
CIMGUI_API void TextEditor_SetReadOnlyEnabled(TextEditor* self,bool value)
{
    return self->SetReadOnlyEnabled(value);
}
CIMGUI_API bool TextEditor_IsReadOnlyEnabled(TextEditor* self)
{
    return self->IsReadOnlyEnabled();
}
CIMGUI_API void TextEditor_SetCaretsVisible(TextEditor* self,bool value)
{
    return self->SetCaretsVisible(value);
}
CIMGUI_API bool TextEditor_IsCaretsVisible(TextEditor* self)
{
    return self->IsCaretsVisible();
}
CIMGUI_API void TextEditor_SetAutoIndentEnabled(TextEditor* self,bool value)
{
    return self->SetAutoIndentEnabled(value);
}
CIMGUI_API bool TextEditor_IsAutoIndentEnabled(TextEditor* self)
{
    return self->IsAutoIndentEnabled();
}
CIMGUI_API void TextEditor_SetShowWhitespacesEnabled(TextEditor* self,bool value)
{
    return self->SetShowWhitespacesEnabled(value);
}
CIMGUI_API bool TextEditor_IsShowWhitespacesEnabled(TextEditor* self)
{
    return self->IsShowWhitespacesEnabled();
}
CIMGUI_API void TextEditor_SetShowSpacesEnabled(TextEditor* self,bool value)
{
    return self->SetShowSpacesEnabled(value);
}
CIMGUI_API bool TextEditor_IsShowSpacesEnabled(TextEditor* self)
{
    return self->IsShowSpacesEnabled();
}
CIMGUI_API void TextEditor_SetShowTabsEnabled(TextEditor* self,bool value)
{
    return self->SetShowTabsEnabled(value);
}
CIMGUI_API bool TextEditor_IsShowTabsEnabled(TextEditor* self)
{
    return self->IsShowTabsEnabled();
}
CIMGUI_API void TextEditor_SetShowLineNumbersEnabled(TextEditor* self,bool value)
{
    return self->SetShowLineNumbersEnabled(value);
}
CIMGUI_API bool TextEditor_IsShowLineNumbersEnabled(TextEditor* self)
{
    return self->IsShowLineNumbersEnabled();
}
CIMGUI_API void TextEditor_SetShowMiniMapEnabled(TextEditor* self,bool value)
{
    return self->SetShowMiniMapEnabled(value);
}
CIMGUI_API bool TextEditor_IsShowMiniMapEnabled(TextEditor* self)
{
    return self->IsShowMiniMapEnabled();
}
CIMGUI_API void TextEditor_SetMiniMapColumns(TextEditor* self,size_t value)
{
    return self->SetMiniMapColumns(value);
}
CIMGUI_API size_t TextEditor_GetMiniMapColumns(TextEditor* self)
{
    return self->GetMiniMapColumns();
}
CIMGUI_API void TextEditor_SetShowScrollbarMiniMapEnabled(TextEditor* self,bool value)
{
    return self->SetShowScrollbarMiniMapEnabled(value);
}
CIMGUI_API bool TextEditor_IsShowScrollbarMiniMapEnabled(TextEditor* self)
{
    return self->IsShowScrollbarMiniMapEnabled();
}
CIMGUI_API void TextEditor_SetShowPanScrollIndicatorEnabled(TextEditor* self,bool value)
{
    return self->SetShowPanScrollIndicatorEnabled(value);
}
CIMGUI_API bool TextEditor_IsShowPanScrollIndicatorEnabled(TextEditor* self)
{
    return self->IsShowPanScrollIndicatorEnabled();
}
CIMGUI_API void TextEditor_SetShowMatchingBrackets(TextEditor* self,bool value)
{
    return self->SetShowMatchingBrackets(value);
}
CIMGUI_API bool TextEditor_IsShowingMatchingBrackets(TextEditor* self)
{
    return self->IsShowingMatchingBrackets();
}
CIMGUI_API void TextEditor_SetCompletePairedGlyphs(TextEditor* self,bool value)
{
    return self->SetCompletePairedGlyphs(value);
}
CIMGUI_API bool TextEditor_IsCompletingPairedGlyphs(TextEditor* self)
{
    return self->IsCompletingPairedGlyphs();
}
CIMGUI_API void TextEditor_SetLineFoldingEnabled(TextEditor* self,bool value)
{
    return self->SetLineFoldingEnabled(value);
}
CIMGUI_API bool TextEditor_IsLineFoldingEnabled(TextEditor* self)
{
    return self->IsLineFoldingEnabled();
}
CIMGUI_API void TextEditor_SetOverwriteEnabled(TextEditor* self,bool value)
{
    return self->SetOverwriteEnabled(value);
}
CIMGUI_API bool TextEditor_IsOverwriteEnabled(TextEditor* self)
{
    return self->IsOverwriteEnabled();
}
CIMGUI_API void TextEditor_SetMiddleMousePanMode(TextEditor* self)
{
    return self->SetMiddleMousePanMode();
}
CIMGUI_API void TextEditor_SetMiddleMouseScrollMode(TextEditor* self)
{
    return self->SetMiddleMouseScrollMode();
}
CIMGUI_API bool TextEditor_IsMiddleMousePanMode(TextEditor* self)
{
    return self->IsMiddleMousePanMode();
}
CIMGUI_API void TextEditor_SetLineNumberLeftMargin(TextEditor* self,size_t value)
{
    return self->SetLineNumberLeftMargin(value);
}
CIMGUI_API size_t TextEditor_GetLineNumberLeftMargin(TextEditor* self)
{
    return self->GetLineNumberLeftMargin();
}
CIMGUI_API void TextEditor_SetDecorationLeftMargin(TextEditor* self,size_t value)
{
    return self->SetDecorationLeftMargin(value);
}
CIMGUI_API size_t TextEditor_GetDecorationLeftMargin(TextEditor* self)
{
    return self->GetDecorationLeftMargin();
}
CIMGUI_API void TextEditor_SetTextLeftMargin(TextEditor* self,size_t value)
{
    return self->SetTextLeftMargin(value);
}
CIMGUI_API size_t TextEditor_GetTextLeftMargin(TextEditor* self)
{
    return self->GetTextLeftMargin();
}
CIMGUI_API void TextEditor_SetText(TextEditor* self,const char* text)
{
    return self->SetText(text);
}
CIMGUI_API const char* TextEditor_GetText(TextEditor* self)
{
    static std::string str;
    str.assign(self->GetText());
    return str.c_str();
}
CIMGUI_API const char* TextEditor_GetCursorText(TextEditor* self,size_t cursor)
{
    static std::string str;
    str.assign(self->GetCursorText(cursor));
    return str.c_str();
}
CIMGUI_API const char* TextEditor_GetLineText(TextEditor* self,size_t line)
{
    static std::string str;
    str.assign(self->GetLineText(line));
    return str.c_str();
}
CIMGUI_API const char* TextEditor_GetSectionText_DocPos(TextEditor* self,DocPos_c start,DocPos_c end)
{
    static std::string str;
    str.assign(self->GetSectionText(ConvertToCPP_DocPos(start),ConvertToCPP_DocPos(end)));
    return str.c_str();
}
CIMGUI_API const char* TextEditor_GetSectionText_DocSelection(TextEditor* self,const DocSelection_c selection)
{
    static std::string str;
    str.assign(self->GetSectionText(ConvertToCPP_DocSelection(selection)));
    return str.c_str();
}
CIMGUI_API void TextEditor_ReplaceSectionText_DocPos(TextEditor* self,DocPos_c start,DocPos_c end,const char* text)
{
    return self->ReplaceSectionText(ConvertToCPP_DocPos(start),ConvertToCPP_DocPos(end),text);
}
CIMGUI_API void TextEditor_ReplaceSectionText_DocSelection(TextEditor* self,const DocSelection_c selection,const char* text)
{
    return self->ReplaceSectionText(ConvertToCPP_DocSelection(selection),text);
}
CIMGUI_API void TextEditor_ClearText(TextEditor* self)
{
    return self->ClearText();
}
CIMGUI_API bool TextEditor_IsEmpty(TextEditor* self)
{
    return self->IsEmpty();
}
CIMGUI_API size_t TextEditor_GetLineCount(TextEditor* self)
{
    return self->GetLineCount();
}
CIMGUI_API void TextEditor_Render(TextEditor* self,const char* title,const ImVec2_c size,ImGuiChildFlags childFlags,ImGuiWindowFlags windowFlags)
{
    return self->Render(title,ConvertToCPP_ImVec2(size),childFlags,windowFlags);
}
CIMGUI_API void TextEditor_SetFocus(TextEditor* self)
{
    return self->SetFocus();
}
CIMGUI_API void TextEditor_Cut(TextEditor* self)
{
    return self->Cut();
}
CIMGUI_API void TextEditor_Copy(TextEditor* self)
{
    return self->Copy();
}
CIMGUI_API void TextEditor_Paste(TextEditor* self)
{
    return self->Paste();
}
CIMGUI_API void TextEditor_Undo(TextEditor* self)
{
    return self->Undo();
}
CIMGUI_API void TextEditor_Redo(TextEditor* self)
{
    return self->Redo();
}
CIMGUI_API bool TextEditor_CanUndo(TextEditor* self)
{
    return self->CanUndo();
}
CIMGUI_API bool TextEditor_CanRedo(TextEditor* self)
{
    return self->CanRedo();
}
CIMGUI_API size_t TextEditor_GetUndoIndex(TextEditor* self)
{
    return self->GetUndoIndex();
}
CIMGUI_API void TextEditor_SelectAll(TextEditor* self)
{
    return self->SelectAll();
}
CIMGUI_API void TextEditor_SelectLine(TextEditor* self,size_t line)
{
    return self->SelectLine(line);
}
CIMGUI_API void TextEditor_SelectLines(TextEditor* self,size_t start,size_t end)
{
    return self->SelectLines(start,end);
}
CIMGUI_API void TextEditor_SelectRegion(TextEditor* self,DocPos_c start,DocPos_c end)
{
    return self->SelectRegion(ConvertToCPP_DocPos(start),ConvertToCPP_DocPos(end));
}
CIMGUI_API void TextEditor_SelectToBrackets(TextEditor* self,bool includeBrackets)
{
    return self->SelectToBrackets(includeBrackets);
}
CIMGUI_API void TextEditor_GrowSelections(TextEditor* self)
{
    return self->GrowSelections();
}
CIMGUI_API void TextEditor_ShrinkSelections(TextEditor* self)
{
    return self->ShrinkSelections();
}
CIMGUI_API void TextEditor_AddNextOccurrence(TextEditor* self)
{
    return self->AddNextOccurrence();
}
CIMGUI_API void TextEditor_SelectAllOccurrences(TextEditor* self)
{
    return self->SelectAllOccurrences();
}
CIMGUI_API bool TextEditor_AnyCursorHasSelection(TextEditor* self)
{
    return self->AnyCursorHasSelection();
}
CIMGUI_API bool TextEditor_AllCursorsHaveSelection(TextEditor* self)
{
    return self->AllCursorsHaveSelection();
}
CIMGUI_API bool TextEditor_CurrentCursorHasSelection(TextEditor* self)
{
    return self->CurrentCursorHasSelection();
}
CIMGUI_API void TextEditor_ClearCursors(TextEditor* self)
{
    return self->ClearCursors();
}
CIMGUI_API size_t TextEditor_GetNumberOfCursors(TextEditor* self)
{
    return self->GetNumberOfCursors();
}
CIMGUI_API DocPos_c TextEditor_GetCursorPosition(TextEditor* self,size_t cursor)
{
    return ConvertFromCPP_DocPos(self->GetCursorPosition(cursor));
}
CIMGUI_API DocPos_c TextEditor_GetMainCursorPosition(TextEditor* self)
{
    return ConvertFromCPP_DocPos(self->GetMainCursorPosition());
}
CIMGUI_API DocPos_c TextEditor_GetCurrentCursorPosition(TextEditor* self)
{
    return ConvertFromCPP_DocPos(self->GetCurrentCursorPosition());
}
CIMGUI_API DocSelection_c TextEditor_GetCursorSelection(TextEditor* self,size_t cursor)
{
    return ConvertFromCPP_DocSelection(self->GetCursorSelection(cursor));
}
CIMGUI_API DocSelection_c TextEditor_GetMainCursorSelection(TextEditor* self)
{
    return ConvertFromCPP_DocSelection(self->GetMainCursorSelection());
}
CIMGUI_API DocSelection_c TextEditor_GetCurrentCursorSelection(TextEditor* self)
{
    return ConvertFromCPP_DocSelection(self->GetCurrentCursorSelection());
}
CIMGUI_API bool TextEditor_IsMousePosOverGlyph(TextEditor* self,const ImVec2_c mousePos)
{
    return self->IsMousePosOverGlyph(ConvertToCPP_ImVec2(mousePos));
}
CIMGUI_API DocPos_c TextEditor_GetDocPosAtMousePos(TextEditor* self,const ImVec2_c mousePos)
{
    return ConvertFromCPP_DocPos(self->GetDocPosAtMousePos(ConvertToCPP_ImVec2(mousePos)));
}
CIMGUI_API const char* TextEditor_GetWordAtMousePos(TextEditor* self,const ImVec2_c mousePos)
{
    static std::string str;
    str.assign(self->GetWordAtMousePos(ConvertToCPP_ImVec2(mousePos)));
    return str.c_str();
}
CIMGUI_API void TextEditor_ScrollToLine(TextEditor* self,size_t line,Scroll alignment)
{
    return self->ScrollToLine(line,alignment);
}
CIMGUI_API size_t TextEditor_GetFirstVisibleRow(TextEditor* self)
{
    return self->GetFirstVisibleRow();
}
CIMGUI_API size_t TextEditor_GetLastVisibleRow(TextEditor* self)
{
    return self->GetLastVisibleRow();
}
CIMGUI_API size_t TextEditor_GetFirstVisibleColumn(TextEditor* self)
{
    return self->GetFirstVisibleColumn();
}
CIMGUI_API size_t TextEditor_GetLastVisibleColumn(TextEditor* self)
{
    return self->GetLastVisibleColumn();
}
CIMGUI_API void TextEditor_SetCursor(TextEditor* self,DocPos_c pos)
{
    return self->SetCursor(ConvertToCPP_DocPos(pos));
}
CIMGUI_API float TextEditor_GetLineHeight(TextEditor* self)
{
    return self->GetLineHeight();
}
CIMGUI_API float TextEditor_GetGlyphWidth(TextEditor* self)
{
    return self->GetGlyphWidth();
}
CIMGUI_API VisPos_c TextEditor_DocPos2VisPos(TextEditor* self,DocPos_c pos)
{
    return ConvertFromCPP_VisPos(self->DocPos2VisPos(ConvertToCPP_DocPos(pos)));
}
CIMGUI_API DocPos_c TextEditor_VisPos2DocPos(TextEditor* self,VisPos_c pos)
{
    return ConvertFromCPP_DocPos(self->VisPos2DocPos(ConvertToCPP_VisPos(pos)));
}
CIMGUI_API bool TextEditor_IsDocPosVisible(TextEditor* self,DocPos_c pos)
{
    return self->IsDocPosVisible(ConvertToCPP_DocPos(pos));
}
CIMGUI_API bool TextEditor_IsVisPosOverGlyph(TextEditor* self,VisPos_c pos)
{
    return self->IsVisPosOverGlyph(ConvertToCPP_VisPos(pos));
}
CIMGUI_API void TextEditor_SelectFirstOccurrenceOf(TextEditor* self,const char* text,bool caseSensitive,bool wholeWord)
{
    return self->SelectFirstOccurrenceOf(text,caseSensitive,wholeWord);
}
CIMGUI_API void TextEditor_SelectNextOccurrenceOf(TextEditor* self,const char* text,bool caseSensitive,bool wholeWord)
{
    return self->SelectNextOccurrenceOf(text,caseSensitive,wholeWord);
}
CIMGUI_API void TextEditor_SelectAllOccurrencesOf(TextEditor* self,const char* text,bool caseSensitive,bool wholeWord)
{
    return self->SelectAllOccurrencesOf(text,caseSensitive,wholeWord);
}
CIMGUI_API void TextEditor_ReplaceTextInCurrentCursor(TextEditor* self,const char* text)
{
    return self->ReplaceTextInCurrentCursor(text);
}
CIMGUI_API void TextEditor_ReplaceTextInAllCursors(TextEditor* self,const char* text)
{
    return self->ReplaceTextInAllCursors(text);
}
CIMGUI_API void TextEditor_OpenFindReplaceWindow(TextEditor* self)
{
    return self->OpenFindReplaceWindow();
}
CIMGUI_API void TextEditor_CloseFindReplaceWindow(TextEditor* self)
{
    return self->CloseFindReplaceWindow();
}
CIMGUI_API void TextEditor_SetFindButtonLabel(TextEditor* self,const char* label)
{
    return self->SetFindButtonLabel(label);
}
CIMGUI_API void TextEditor_SetFindAllButtonLabel(TextEditor* self,const char* label)
{
    return self->SetFindAllButtonLabel(label);
}
CIMGUI_API void TextEditor_SetReplaceButtonLabel(TextEditor* self,const char* label)
{
    return self->SetReplaceButtonLabel(label);
}
CIMGUI_API void TextEditor_SetReplaceAllButtonLabel(TextEditor* self,const char* label)
{
    return self->SetReplaceAllButtonLabel(label);
}
CIMGUI_API bool TextEditor_HasFindString(TextEditor* self)
{
    return self->HasFindString();
}
CIMGUI_API void TextEditor_FindNext(TextEditor* self)
{
    return self->FindNext();
}
CIMGUI_API void TextEditor_FindAll(TextEditor* self)
{
    return self->FindAll();
}
CIMGUI_API void TextEditor_AddMarker(TextEditor* self,size_t line,ImU32 lineNumberColor,ImU32 textColor,const char* lineNumberTooltip,const char* textTooltip)
{
    return self->AddMarker(line,lineNumberColor,textColor,lineNumberTooltip,textTooltip);
}
CIMGUI_API void TextEditor_ClearMarkers(TextEditor* self)
{
    return self->ClearMarkers();
}
CIMGUI_API bool TextEditor_HasMarkers(TextEditor* self)
{
    return self->HasMarkers();
}
CIMGUI_API void TextEditor_AddSquiggle(TextEditor* self,DocPos_c start,DocPos_c end,size_t type,ImU32 color,const char* tooltip)
{
    return self->AddSquiggle(ConvertToCPP_DocPos(start),ConvertToCPP_DocPos(end),type,color,tooltip);
}
CIMGUI_API void TextEditor_ClearSquiggles_DocPos(TextEditor* self,DocPos_c start,DocPos_c end)
{
    return self->ClearSquiggles(ConvertToCPP_DocPos(start),ConvertToCPP_DocPos(end));
}
CIMGUI_API void TextEditor_ClearSquiggles_size_t(TextEditor* self,size_t type)
{
    return self->ClearSquiggles(type);
}
CIMGUI_API void TextEditor_ClearSquiggles_Nil(TextEditor* self)
{
    return self->ClearSquiggles();
}
CIMGUI_API bool TextEditor_HasSquiggles(TextEditor* self)
{
    return self->HasSquiggles();
}
CIMGUI_API void TextEditor_SetChangeCallback(TextEditor* self,void(*cb)(),int delay)
{
    return self->SetChangeCallback([cb](){cb();},delay);
}
CIMGUI_API void TextEditor_SetInsertor(TextEditor* self,void*(*cb)(size_t))
{
    return self->SetInsertor([cb](size_t line){return cb(line);});
}
CIMGUI_API void TextEditor_SetDeletor(TextEditor* self,void(*cb)(size_t,void*))
{
    return self->SetDeletor([cb](size_t line,void* data){cb(line,data);});
}
CIMGUI_API void TextEditor_SetUserData(TextEditor* self,size_t line,void* data)
{
    return self->SetUserData(line,data);
}
CIMGUI_API void* TextEditor_GetUserData(TextEditor* self,size_t line)
{
    return self->GetUserData(line);
}
CIMGUI_API void TextEditor_IterateUserData(TextEditor* self,void(*cb)(size_t,void*))
{
    return self->IterateUserData([cb](size_t line,void* data){cb(line,data);});
}
CIMGUI_API void TextEditor_SetLineDecorator(TextEditor* self,size_t width,void(*cb)(Decorator*))
{
    return self->SetLineDecorator(width,[cb](Decorator& decorator){cb(&decorator);});
}
CIMGUI_API void TextEditor_ClearLineDecorator(TextEditor* self)
{
    return self->ClearLineDecorator();
}
CIMGUI_API bool TextEditor_HasLineDecorator(TextEditor* self)
{
    return self->HasLineDecorator();
}
CIMGUI_API void TextEditor_SetLineNumberContextMenuCallback(TextEditor* self,void(*cb)(PopupData*))
{
    return self->SetLineNumberContextMenuCallback([cb](PopupData& data){cb(&data);});
}
CIMGUI_API void TextEditor_ClearLineNumberContextMenuCallback(TextEditor* self)
{
    return self->ClearLineNumberContextMenuCallback();
}
CIMGUI_API bool TextEditor_HasLineNumberContextMenuCallback(TextEditor* self)
{
    return self->HasLineNumberContextMenuCallback();
}
CIMGUI_API void TextEditor_SetTextContextMenuCallback(TextEditor* self,void(*cb)(PopupData*))
{
    return self->SetTextContextMenuCallback([cb](PopupData& data){cb(&data);});
}
CIMGUI_API void TextEditor_ClearTextContextMenuCallback(TextEditor* self)
{
    return self->ClearTextContextMenuCallback();
}
CIMGUI_API bool TextEditor_HasTextContextMenuCallback(TextEditor* self)
{
    return self->HasTextContextMenuCallback();
}
CIMGUI_API void TextEditor_SetTextHoverCallback(TextEditor* self,void(*cb)(PopupData*))
{
    return self->SetTextHoverCallback([cb](PopupData& data){cb(&data);});
}
CIMGUI_API void TextEditor_ClearTextHoverCallback(TextEditor* self)
{
    return self->ClearTextHoverCallback();
}
CIMGUI_API bool TextEditor_HasTextHoverCallback(TextEditor* self)
{
    return self->HasTextHoverCallback();
}
CIMGUI_API void TextEditor_FoldAroundLine(TextEditor* self,size_t line)
{
    return self->FoldAroundLine(line);
}
CIMGUI_API void TextEditor_UnfoldAroundLine(TextEditor* self,size_t line)
{
    return self->UnfoldAroundLine(line);
}
CIMGUI_API void TextEditor_ToggleAtLine(TextEditor* self,size_t line)
{
    return self->ToggleAtLine(line);
}
CIMGUI_API void TextEditor_UnfoldAll(TextEditor* self)
{
    return self->UnfoldAll();
}
CIMGUI_API bool TextEditor_IsLineFoldable(TextEditor* self,size_t line)
{
    return self->IsLineFoldable(line);
}
CIMGUI_API bool TextEditor_IsLineFolded(TextEditor* self,size_t line)
{
    return self->IsLineFolded(line);
}
CIMGUI_API bool TextEditor_IsLineVisible(TextEditor* self,size_t line)
{
    return self->IsLineVisible(line);
}
CIMGUI_API bool TextEditor_IsLineHidden(TextEditor* self,size_t line)
{
    return self->IsLineHidden(line);
}
CIMGUI_API void TextEditor_IndentLines(TextEditor* self)
{
    return self->IndentLines();
}
CIMGUI_API void TextEditor_DeindentLines(TextEditor* self)
{
    return self->DeindentLines();
}
CIMGUI_API void TextEditor_MoveUpLines(TextEditor* self)
{
    return self->MoveUpLines();
}
CIMGUI_API void TextEditor_MoveDownLines(TextEditor* self)
{
    return self->MoveDownLines();
}
CIMGUI_API void TextEditor_ToggleComments(TextEditor* self)
{
    return self->ToggleComments();
}
CIMGUI_API void TextEditor_FilterSelections(TextEditor* self,const char*(*cb)(const char*))
{
    return self->FilterSelections([cb](std::string_view noname1){return std::string(cb(noname1.data()));});
}
CIMGUI_API void TextEditor_SelectionToLowerCase(TextEditor* self)
{
    return self->SelectionToLowerCase();
}
CIMGUI_API void TextEditor_SelectionToUpperCase(TextEditor* self)
{
    return self->SelectionToUpperCase();
}
CIMGUI_API void TextEditor_StripTrailingWhitespaces(TextEditor* self)
{
    return self->StripTrailingWhitespaces();
}
CIMGUI_API void TextEditor_FilterLines(TextEditor* self,const char*(*cb)(const char*))
{
    return self->FilterLines([cb](std::string_view noname1){return std::string(cb(noname1.data()));});
}
CIMGUI_API void TextEditor_TabsToSpaces(TextEditor* self)
{
    return self->TabsToSpaces();
}
CIMGUI_API void TextEditor_SpacesToTabs(TextEditor* self)
{
    return self->SpacesToTabs();
}
CIMGUI_API ImU32 Palette_get(Palette* self,Color color)
{
    return self->get(color);
}
CIMGUI_API void TextEditor_SetPalette(TextEditor* self,const Palette* newPalette)
{
    return self->SetPalette(*newPalette);
}
CIMGUI_API const Palette* TextEditor_GetPalette(TextEditor* self)
{
    return &self->GetPalette();
}
CIMGUI_API void TextEditor_SetDefaultPalette(const Palette* aValue)
{
    return TextEditor::SetDefaultPalette(*aValue);
}
CIMGUI_API Palette* TextEditor_GetDefaultPalette()
{
    return &TextEditor::GetDefaultPalette();
}
CIMGUI_API const Palette* TextEditor_GetDarkPalette()
{
    return &TextEditor::GetDarkPalette();
}
CIMGUI_API const Palette* TextEditor_GetLightPalette()
{
    return &TextEditor::GetLightPalette();
}
CIMGUI_API Glyph* Glyph_Glyph_Nil(void)
{
    return IM_NEW(Glyph)();
}
CIMGUI_API void Glyph_destroy(Glyph* self)
{
    IM_DELETE(self);
}
CIMGUI_API Glyph* Glyph_Glyph_Wchar(ImWchar cp)
{
    return IM_NEW(Glyph)(cp);
}
CIMGUI_API Glyph* Glyph_Glyph_WcharColor(ImWchar cp,Color col)
{
    return IM_NEW(Glyph)(cp,col);
}
CIMGUI_API Iterator* Iterator_Iterator_Nil(void)
{
    return IM_NEW(Iterator)();
}
CIMGUI_API void Iterator_destroy(Iterator* self)
{
    IM_DELETE(self);
}
CIMGUI_API Iterator* Iterator_Iterator_GlyphPtr(Glyph* g)
{
    return IM_NEW(Iterator)(g);
}
CIMGUI_API const Language* Language_C()
{
    return TextEditor::Language::C();
}
CIMGUI_API const Language* Language_Cpp()
{
    return TextEditor::Language::Cpp();
}
CIMGUI_API const Language* Language_Cs()
{
    return TextEditor::Language::Cs();
}
CIMGUI_API const Language* Language_AngelScript()
{
    return TextEditor::Language::AngelScript();
}
CIMGUI_API const Language* Language_Lua()
{
    return TextEditor::Language::Lua();
}
CIMGUI_API const Language* Language_Python()
{
    return TextEditor::Language::Python();
}
CIMGUI_API const Language* Language_Glsl()
{
    return TextEditor::Language::Glsl();
}
CIMGUI_API const Language* Language_Hlsl()
{
    return TextEditor::Language::Hlsl();
}
CIMGUI_API const Language* Language_Json()
{
    return TextEditor::Language::Json();
}
CIMGUI_API const Language* Language_Markdown()
{
    return TextEditor::Language::Markdown();
}
CIMGUI_API const Language* Language_Sql()
{
    return TextEditor::Language::Sql();
}
CIMGUI_API void TextEditor_SetLanguage(TextEditor* self,const Language* language)
{
    return self->SetLanguage(language);
}
CIMGUI_API const Language* TextEditor_GetLanguage(TextEditor* self)
{
    return self->GetLanguage();
}
CIMGUI_API bool TextEditor_HasLanguage(TextEditor* self)
{
    return self->HasLanguage();
}
CIMGUI_API const char* TextEditor_GetLanguageName(TextEditor* self)
{
    static std::string str;
    str.assign(self->GetLanguageName());
    return str.c_str();
}
CIMGUI_API void TextEditor_SetLanguageChangeCallback(TextEditor* self,void(*cb)())
{
    return self->SetLanguageChangeCallback([cb](){cb();});
}
CIMGUI_API void TextEditor_IterateIdentifiers(TextEditor* self,void(*cb)(const char*))
{
    return self->IterateIdentifiers([cb](const std::string& identifier){cb(identifier.c_str());});
}
CIMGUI_API void TextEditor_SetAutoCompleteConfig(TextEditor* self,const AutoCompleteConfig* autoCompleteConfig)
{
    return self->SetAutoCompleteConfig(autoCompleteConfig);
}
CIMGUI_API size_t CodePoint_write(char* i,ImWchar codepoint)
{
    return TextEditor::CodePoint::write(i,codepoint);
}
CIMGUI_API bool CodePoint_isLetter(ImWchar codepoint)
{
    return TextEditor::CodePoint::isLetter(codepoint);
}
CIMGUI_API bool CodePoint_isNumber(ImWchar codepoint)
{
    return TextEditor::CodePoint::isNumber(codepoint);
}
CIMGUI_API bool CodePoint_isWord(ImWchar codepoint)
{
    return TextEditor::CodePoint::isWord(codepoint);
}
CIMGUI_API bool CodePoint_isWhiteSpace(ImWchar codepoint)
{
    return TextEditor::CodePoint::isWhiteSpace(codepoint);
}
CIMGUI_API bool CodePoint_isXidStart(ImWchar codepoint)
{
    return TextEditor::CodePoint::isXidStart(codepoint);
}
CIMGUI_API bool CodePoint_isXidContinue(ImWchar codepoint)
{
    return TextEditor::CodePoint::isXidContinue(codepoint);
}
CIMGUI_API bool CodePoint_isLower(ImWchar codepoint)
{
    return TextEditor::CodePoint::isLower(codepoint);
}
CIMGUI_API bool CodePoint_isUpper(ImWchar codepoint)
{
    return TextEditor::CodePoint::isUpper(codepoint);
}
CIMGUI_API bool CodePoint_isEastAsian(ImWchar codepoint)
{
    return TextEditor::CodePoint::isEastAsian(codepoint);
}
CIMGUI_API ImWchar CodePoint_toUpper(ImWchar codepoint)
{
    return TextEditor::CodePoint::toUpper(codepoint);
}
CIMGUI_API ImWchar CodePoint_toLower(ImWchar codepoint)
{
    return TextEditor::CodePoint::toLower(codepoint);
}
CIMGUI_API bool CodePoint_isPairOpener(ImWchar ch)
{
    return TextEditor::CodePoint::isPairOpener(ch);
}
CIMGUI_API bool CodePoint_isPairCloser(ImWchar ch)
{
    return TextEditor::CodePoint::isPairCloser(ch);
}
CIMGUI_API ImWchar CodePoint_toPairCloser(ImWchar ch)
{
    return TextEditor::CodePoint::toPairCloser(ch);
}
CIMGUI_API ImWchar CodePoint_toPairOpener(ImWchar ch)
{
    return TextEditor::CodePoint::toPairOpener(ch);
}
CIMGUI_API bool CodePoint_isMatchingPair(ImWchar open,ImWchar close)
{
    return TextEditor::CodePoint::isMatchingPair(open,close);
}
CIMGUI_API bool CodePoint_isBracketOpener(ImWchar ch)
{
    return TextEditor::CodePoint::isBracketOpener(ch);
}
CIMGUI_API bool CodePoint_isBracketCloser(ImWchar ch)
{
    return TextEditor::CodePoint::isBracketCloser(ch);
}
CIMGUI_API bool CodePoint_isMatchingBrackets(ImWchar open,ImWchar close)
{
    return TextEditor::CodePoint::isMatchingBrackets(open,close);
}
CIMGUI_API void TextEditor_SetLineBreakConfig(TextEditor* self,LineBreakConfig* newConfig)
{
    return self->SetLineBreakConfig(*newConfig);
}
CIMGUI_API void TextEditor_SetImGuiContext(ImGuiContext* ctx)
{
    return TextEditor::SetImGuiContext(ctx);
}
CIMGUI_API TextDiff* TextDiff_TextDiff(void)
{
    return IM_NEW(TextDiff)();
}
CIMGUI_API void TextDiff_destroy(TextDiff* self)
{
    IM_DELETE(self);
}
CIMGUI_API void TextDiff_SetSideBySideMode(TextDiff* self,bool flag)
{
    return self->SetSideBySideMode(flag);
}
CIMGUI_API bool TextDiff_GetSideBySideMode(TextDiff* self)
{
    return self->GetSideBySideMode();
}
CIMGUI_API void TextDiff_SetTabSize(TextDiff* self,size_t value)
{
    return self->SetTabSize(value);
}
CIMGUI_API size_t TextDiff_GetTabSize(TextDiff* self)
{
    return self->GetTabSize();
}
CIMGUI_API void TextDiff_SetLineSpacing(TextDiff* self,float value)
{
    return self->SetLineSpacing(value);
}
CIMGUI_API float TextDiff_GetLineSpacing(TextDiff* self)
{
    return self->GetLineSpacing();
}
CIMGUI_API void TextDiff_SetWordWrapEnabled(TextDiff* self,bool value)
{
    return self->SetWordWrapEnabled(value);
}
CIMGUI_API bool TextDiff_IsWordWrapEnabled(TextDiff* self)
{
    return self->IsWordWrapEnabled();
}
CIMGUI_API void TextDiff_SetShowWhitespacesEnabled(TextDiff* self,bool value)
{
    return self->SetShowWhitespacesEnabled(value);
}
CIMGUI_API bool TextDiff_IsShowWhitespacesEnabled(TextDiff* self)
{
    return self->IsShowWhitespacesEnabled();
}
CIMGUI_API void TextDiff_SetShowSpacesEnabled(TextDiff* self,bool value)
{
    return self->SetShowSpacesEnabled(value);
}
CIMGUI_API bool TextDiff_IsShowSpacesEnabled(TextDiff* self)
{
    return self->IsShowSpacesEnabled();
}
CIMGUI_API void TextDiff_SetShowTabsEnabled(TextDiff* self,bool value)
{
    return self->SetShowTabsEnabled(value);
}
CIMGUI_API bool TextDiff_IsShowTabsEnabled(TextDiff* self)
{
    return self->IsShowTabsEnabled();
}
CIMGUI_API void TextDiff_SetShowScrollbarMiniMapEnabled(TextDiff* self,bool value)
{
    return self->SetShowScrollbarMiniMapEnabled(value);
}
CIMGUI_API bool TextDiff_IsShowScrollbarMiniMapEnabled(TextDiff* self)
{
    return self->IsShowScrollbarMiniMapEnabled();
}
CIMGUI_API void TextDiff_SetLanguage(TextDiff* self,const Language* language)
{
    return self->SetLanguage(language);
}
CIMGUI_API const Language* TextDiff_GetLanguage(TextDiff* self)
{
    return self->GetLanguage();
}
CIMGUI_API void TextDiff_SetColors(TextDiff* self,ImU32 ac,ImU32 dc)
{
    return self->SetColors(ac,dc);
}
CIMGUI_API void TextDiff_SetPalette(TextDiff* self,const Palette* newPalette)
{
    return self->SetPalette(*newPalette);
}
CIMGUI_API const Palette* TextDiff_GetPalette(TextDiff* self)
{
    return &self->GetPalette();
}
CIMGUI_API void TextDiff_SetFocus(TextDiff* self)
{
    return self->SetFocus();
}
CIMGUI_API void TextDiff_SetText(TextDiff* self,const char* left,const char* right)
{
    return self->SetText(left,right);
}
CIMGUI_API void TextDiff_Render(TextDiff* self,const char* title,const ImVec2_c size,ImGuiChildFlags childFlags,ImGuiWindowFlags windowFlags)
{
    return self->Render(title,ConvertToCPP_ImVec2(size),childFlags,windowFlags);
}
CIMGUI_API TrieAutoComplete* TrieAutoComplete_TrieAutoComplete(void)
{
    return IM_NEW(TrieAutoComplete)();
}
CIMGUI_API void TrieAutoComplete_destroy(TrieAutoComplete* self)
{
    IM_DELETE(self);
}
CIMGUI_API void TrieAutoComplete_Connect(TrieAutoComplete* self,TextEditor* editor)
{
    return self->Connect(editor);
}
CIMGUI_API void TrieAutoComplete_Disconnect(TrieAutoComplete* self)
{
    return self->Disconnect();
}
CIMGUI_API bool TrieAutoComplete_IsConnected(TrieAutoComplete* self)
{
    return self->IsConnected();
}
CIMGUI_API Notifications* Notifications_Notifications(void)
{
    return IM_NEW(Notifications)();
}
CIMGUI_API void Notifications_destroy(Notifications* self)
{
    IM_DELETE(self);
}
CIMGUI_API void Notifications_Add(Notifications* self,Type type,const char* message,int dismissTime)
{
    return self->Add(type,std::string(message),dismissTime);
}
CIMGUI_API void Notifications_Render(Notifications* self,ImVec2_c pos)
{
    return self->Render(ConvertToCPP_ImVec2(pos));
}

////////////////manually generated
CIMGUI_API Palette* Palette_Palette()
{
    return IM_NEW(Palette)();
}
CIMGUI_API void Palette_destroy(Palette* self)
{
    IM_DELETE(self);
}
CIMGUI_API void Palette_set(Palette* self,ImU32 col,int pos)
{
    (*self)[pos] = col;
}
CIMGUI_API ImU32 Palette_const_get(const Palette* self,Color color)
{
    return self->get(color);
}
CIMGUI_API char* TextEditor_GetText_alloc(TextEditor* self)
{
    std::string str = self->GetText();
    char* cStr = (char*)IM_ALLOC(str.size() + 1); // Allocate memory
    std::strcpy(cStr, str.c_str()); // Copy string contents
    return cStr; // Return new C-style string
}
CIMGUI_API void TextEditor_GetText_free(char* ptr)
{
    IM_FREE(ptr); // free memory
}
CIMGUI_API const char* TextEditor_GetText_static(TextEditor* self)
{
    static std::string str;
    str.assign(self->GetText());
    return str.c_str();
}
////////////Dejavu
CIMGUI_API int GetDejavu(void** deja)
{
	*deja = (void*) &dejavu;
	return dejavuSize;
}
CIMGUI_API void SetDejavu()
{
    auto& io = ImGui::GetIO();
    ImFontConfig config;
    std::memcpy(config.Name, "DejaVu", 7);
    config.FontDataOwnedByAtlas = false;
    config.OversampleH = 1;
    config.OversampleV = 1;
#ifdef IMGUI_ENABLE_FREETYPE
    config.FontLoaderFlags = ImGuiFreeTypeLoaderFlags_MonoHinting;
#endif
    io.Fonts->Clear();
    io.Fonts->AddFontFromMemoryCompressedTTF((void*) &dejavu, dejavuSize, 15.0f, &config);
#ifdef IMGUI_ENABLE_FREETYPE
    io.Fonts->SetFontLoader(ImGuiFreeType::GetFontLoader());
#else
    io.Fonts->SetFontLoader(ImFontAtlasGetFontLoaderForStbTruetype());
#endif
}




