name: Windows test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    #runs-on: ubuntu-latest
    #runs-on: windows-latest
    runs-on: windows-2019
    strategy:
      matrix:
        nim: [ '2.0.6', 'devel' ]
    name: Nim ${{ matrix.nim }} compilation
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Set up MinGW
      #  uses: egor-tensin/setup-mingw@v2
      #  with:
      #    platform: x64
         #platform: x86
      #- run: pacman -S mingw-w64-x86_64-SDL2
      - run: make
