name: Windows test
on: [push]
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: windows-latest
    strategy:
      matrix:
        nim: [ '1.6.12', 'devel' ]
    name: Nim ${{ matrix.nim }} compilation
    steps:
      - uses: actions/checkout@master
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: git clone -b master --single-branch --depth 1 --recursive --shallow-submodules  https://github.com/cimgui/cimgui src/private/cimgui
      - run: git clone -b master --single-branch --depth 1 --recursive --shallow-submodules  https://github.com/cimgui/cimplot src/private/cimplot
      - run: make


