name: Nim compilation

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-latest
    #runs-on: ubuntu-latest
    #
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Nim Compiler
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Set up MinGW
      #  uses: msys2/setup-msys2@v2
      #  with:
      #    msystem: mingw64
      #    install: mingw-w64-x86_64-SDL2
      - name: Windows evnvironment values
      # run: echo ${{ env.CONFIGRATION }}
      - run: make install
        continue-on-error: true
      - run: make
      #
