name: Windows test
on: [push]
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: windows-latest
    strategy:
      matrix:
        nim: [ '1.6.12', 'devel' ]
    name: Nim ${{ matrix.nim }} compilation
    steps:
      - uses: actions/checkout@master
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: git clone --recursive https://github.com/cimgui/cimgui  src/private
      - run: git clone --recursive https://github.com/epezent/implot src/private
      - run: make


