name: Windows test
on: [push]
jobs:
  build:
    #runs-on: ubuntu-latest
    #runs-on: windows-latest
    runs-on: windows-2019
    strategy:
      matrix:
        nim: [ '1.6.20', 'devel' ]
    name: Nim ${{ matrix.nim }} compilation
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      #- name: Set up MinGW
      #  uses: egor-tensin/setup-mingw@v2
      #  with:
      #    platform: x64
         #platform: x86
      #- run: pacman -S mingw-w64-x86_64-SDL2
      - run: make
